# Generated by Django 3.2.7 on 2021-10-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('EventId', models.AutoField(primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=100)),
                ('EventDescription', models.CharField(max_length=1000)),
                ('DateOfEvent', models.DateField()),
                ('EventVenue', models.CharField(max_length=200)),
                ('EventCost', models.IntegerField()),
                ('EventPhotoName', models.CharField(max_length=100)),
            ],
        ),
    ]
