# Generated by Django 3.2.7 on 2021-10-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
