# Generated by Django 3.2.7 on 2021-10-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_events_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventPhotoName',
            field=models.ImageField(upload_to=''),
        ),
    ]
