# Generated by Django 3.2.7 on 2021-10-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_event_eventphotoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='DateOfEvent',
            field=models.DateTimeField(),
        ),
    ]
