# Generated by Django 3.2.4 on 2021-10-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_dateofevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserPhotoName',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
