# Generated by Django 3.2.7 on 2021-10-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_full_name'),
        ('api', '0005_alter_event_dateofevent'),
    ]

    operations = [
    ]
