# Generated by Django 3.2.4 on 2021-10-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211005_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserPhotoName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
