# Generated by Django 3.2.7 on 2021-10-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20211004_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventPhotoName',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
