# Generated by Django 3.2.4 on 2021-10-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20211004_1742'),
        ('api', '0007_alter_user_userphotoname'),
    ]

    operations = [
    ]
