# Generated by Django 3.2.7 on 2021-10-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_event_eventphotoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventPhotoName',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
