# Generated by Django 3.2.7 on 2021-10-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_event_eventphotoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventPhotoName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
