# Generated by Django 3.2.7 on 2021-10-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventPhotoName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
