# Generated by Django 3.2.4 on 2021-10-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventPhotoName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
